### ISSUE TITLE
Blog post on valueboxes and sparklines

### ISSUE THREAD

**Issue by grusheInvestec** [jbkunst/blog#1]
Hi Joshua,

Your blog post on valueboxes and sparklines was really useful, I just wanted to check with you if you submitted a pull request for the shinydashboard and or bs4dash to get it implemented there?

Thanks

Grace

**Comment by jbkunst** [comment]
Hi @grusheInvestec 

I haven't send any PR to implement de valueBoxes with sparklines. IMHO this functionality is beyond the scope of each of those packages.

Kindly regards
